name: Build and Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build flake8
          pip install -e .

      - name: Lint with flake8
        run: |
          flake8 wikitree_api --max-line-length=100 --ignore=E203,W503

      - name: Build package
        run: |
          python -m build
